name: 'Setup Node.js with pnpm'
description: 'Sets up Node.js 20, pnpm (from packageManager), and installs dependencies with caching'

inputs:
  generate-prisma:
    description: 'Whether to generate Prisma client'
    required: false
    default: 'true'
  install-playwright:
    description: 'Whether to install Playwright browsers (chromium only)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      # Reads version automatically from package.json packageManager field

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Generate Prisma client
      if: inputs.generate-prisma == 'true'
      shell: bash
      run: pnpm run db:generate

    - name: Get Playwright version
      if: inputs.install-playwright == 'true'
      id: playwright-version
      shell: bash
      run: |
        VERSION=$(cat package.json | jq -r '.devDependencies["@playwright/test"]')
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Cache Playwright browsers
      if: inputs.install-playwright == 'true'
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ steps.playwright-version.outputs.version }}

    - name: Install Playwright browsers
      if: inputs.install-playwright == 'true' && steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      run: pnpm exec playwright install --with-deps chromium

    - name: Install Playwright system deps only
      if: inputs.install-playwright == 'true' && steps.playwright-cache.outputs.cache-hit == 'true'
      shell: bash
      run: pnpm exec playwright install-deps chromium
